# .rubocop.yml

# We want Exclude directives from different
# config files to get merged, not overwritten
inherit_mode:
  merge:
    - Exclude

require:
  # Standard's config uses custom cops,
  # so it must be loaded along with custom Standard gems
  - standard

inherit_gem:
  standard: config/ruby-2.7.yml

# Global options, like Ruby version
AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 2.7

Naming/FileName:
  Exclude:
    - lib/rubocop-enen.rb
